name: CI

on:
  push:
    branches: [ feature/ci-setup ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.7

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run tests
        run: bundle exec rspec
